### ISSUE TITLE
RuntimeError: Given input size: (512x4x4). Calculated output size: (512x-2x-2). Output size is too smal│ l at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:47

### ISSUE THREAD

**Issue by billhhh** [yanbeic/CCL#5]
Hi,

When I tried to run scripts/run_ccl_ai.sh after generating the json file. I received the error below..

Traceback (most recent call last):                                                                     │
  File "main.py", line 569, in <module>                                                                │
    main_worker(-1, opt)                                                                               │
  File "main.py", line 522, in main_worker                                                             │
    tb_writer=tb_writer, distributed=opt.distributed, image_size=image_size, loss_weight=opt.loss_weigh│
t)                                                                                                     │
  File "/media/data/huwang/experiments/multimodal/CCL/training.py", line 402, in train_ai_epoch        │
    features_img = image_model(images)                                                                 │
  File "/media/data/huwang/program_files/venv/CCL/lib/python3.6/site-packages/torch/nn/modules/module.p│
y", line 493, in __call__                                                                              │
    result = self.forward(*input, **kwargs)                                                            │
  File "/media/data/huwang/program_files/venv/CCL/lib/python3.6/site-packages/torch/nn/parallel/data_pa│
rallel.py", line 152, in forward                                                                       │
    outputs = self.parallel_apply(replicas, inputs, kwargs)                                            │
  File "/media/data/huwang/program_files/venv/CCL/lib/python3.6/site-packages/torch/nn/parallel/data_pa│
rallel.py", line 162, in parallel_apply                                                                │
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])                   │
  File "/media/data/huwang/program_files/venv/CCL/lib/python3.6/site-packages/torch/nn/parallel/paralle│
l_apply.py", line 83, in parallel_apply                                                                │
    raise output                                                                                       │
  File "/media/data/huwang/program_files/venv/CCL/lib/python3.6/site-packages/torch/nn/parallel/paralle│
l_apply.py", line 59, in _worker                                                                       │
    output = module(*input, **kwargs)                                                                  │
  File "/media/data/huwang/program_files/venv/CCL/lib/python3.6/site-packages/torch/nn/modules/module.p│
y", line 493, in __call__                                                                              │
    result = self.forward(*input, **kwargs)                                                            │
  File "/media/data/huwang/program_files/venv/CCL/lib/python3.6/site-packages/torch/nn/modules/containe│
r.py", line 92, in forward                                                                             │
    input = module(input)                                                                              │
  File "/media/data/huwang/program_files/venv/CCL/lib/python3.6/site-packages/torch/nn/modules/module.p│
y", line 493, in __call__                                                                              │
    result = self.forward(*input, **kwargs)                                                            │
  File "/media/data/huwang/program_files/venv/CCL/lib/python3.6/site-packages/torch/nn/modules/pooling.│
py", line 563, in forward                                                                              │
    self.padding, self.ceil_mode, self.count_include_pad)                                              │
RuntimeError: Given input size: (512x4x4). Calculated output size: (512x-2x-2). Output size is too smal│
l at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:47

Can you offer some help.. Thank you

**Comment by billhhh** [comment]
Figured out, --image_size 224. Thx anyway
